VOCAB = 32_000
D_MODEL = 224
N_HEADS = 4
HEAD_DIM = 56
N_LAYERS = 4
FFN_MULT = 4
ROPE_DIM = 24
NUM_BASES = 4
ASLA_LATENT = 40
ASLA_KV_HEADS = 2
ASLA_Q_RANK = 64
MLA_Q_RANK = 65
MLA_KV_RANK = 69
SEQ_LEN = 256

ASLA_THEORETICAL_CACHE = ASLA_LATENT + NUM_BASES  # latent state + routing weights
MLA_THEORETICAL_CACHE = MLA_KV_RANK + ROPE_DIM   # c^KV + decoupled RoPE key
